
Software_Version_20260913_090252="""
-- ====================================
-- Data for [API].[FunctionParameters]
-- ====================================

SET IDENTITY_INSERT [API].[FunctionParameters] ON;

INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (1, 'CradleSessionID', 'BIGINT', 1, '2026-09-13 04:55:58.803', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (2, 'ProcessRecordID', 'BIGINT', 2, '2026-09-13 04:55:58.867', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (3, 'PassFail', 'BIT', 2, '2026-09-13 04:55:58.873', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (4, 'Reason', 'VARCHAR', 2, '2026-09-13 04:55:58.880', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (5, 'StationEQ', 'VARCHAR', 3, '2026-09-13 04:55:58.897', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (6, 'CradleEQ', 'VARCHAR', 3, '2026-09-13 04:55:58.903', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (7, 'StationRecordID', 'BIGINT', 4, '2026-09-13 04:55:58.923', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (8, 'CradleSessionID', 'BIGINT', 4, '2026-09-13 04:55:58.930', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (9, 'ModuleEQ', 'VARCHAR', 4, '2026-09-13 04:55:58.937', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (10, 'ModuleFirmwareSoftwareNumber', 'VARCHAR', 4, '2026-09-13 04:55:58.940', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (11, 'ModuleFirmwareVersion', 'VARCHAR', 4, '2026-09-13 04:55:58.947', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (12, 'UFID', 'VARCHAR', 4, '2026-09-13 04:55:58.953', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (13, 'StationEQNumber', 'VARCHAR', 5, '2026-09-13 04:55:58.977', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (14, 'BathFxEqNumber', 'VARCHAR', 5, '2026-09-13 04:55:58.983', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (15, 'BathRecipeName', 'VARCHAR', 5, '2026-09-13 04:55:58.990', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (16, 'SxPartNumber', 'VARCHAR', 5, '2026-09-13 04:55:58.997', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (17, 'SxLotID', 'VARCHAR', 5, '2026-09-13 04:55:59.003', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (18, 'SxRecipeName', 'VARCHAR', 5, '2026-09-13 04:55:59.010', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (19, 'SetupUserID', 'VARCHAR', 5, '2026-09-13 04:55:59.013', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (20, 'SxPartName', 'VARCHAR', 6, '2026-09-13 04:55:59.047', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (21, 'RecipeDurationDays', 'FLOAT', 6, '2026-09-13 04:55:59.050', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (22, 'OnlyProduction', 'BIT', 6, '2026-09-13 04:55:59.057', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (23, 'ActiveOnly', 'BIT', 6, '2026-09-13 04:55:59.063', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (24, 'BathRecipeName', 'VARCHAR', 7, '2026-09-13 04:55:59.080', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (25, 'CradleEQ', 'VARCHAR', 8, '2026-09-13 04:55:59.097', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (26, 'ProcessRecordID', 'BIGINT', 9, '2026-09-13 04:55:59.127', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (27, 'EQSerialNumber', 'VARCHAR', 9, '2026-09-13 04:55:59.133', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (28, 'StartDateTimeOffset', 'DATETIMEOFFSET', 9, '2026-09-13 04:55:59.140', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (29, 'EndDateTimeOffset', 'DATETIMEOFFSET', 9, '2026-09-13 04:55:59.147', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (30, 'ActiveOnly', 'BIT', 10, '2026-09-13 04:55:59.163', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (31, 'ProcessRecordID', 'BIGINT', 11, '2026-09-13 04:55:59.183', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (32, 'PageSize', 'INT', 11, '2026-09-13 04:55:59.190', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (33, 'AfterReadDateTimeOffset', 'DATETIMEOFFSET', 11, '2026-09-13 04:55:59.197', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (34, 'RecipeID', 'INT', 12, '2026-09-13 04:55:59.213', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (35, 'ProcessRecordID', 'BIGINT', 13, '2026-09-13 04:55:59.240', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (36, 'LotNumber', 'VARCHAR', 13, '2026-09-13 04:55:59.247', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (37, 'UFID', 'VARCHAR', 13, '2026-09-13 04:55:59.253', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (38, 'Position', 'CHAR', 13, '2026-09-13 04:55:59.260', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (39, 'MachineName', 'VARCHAR', 14, '2026-09-13 04:55:59.273', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (40, 'ModuleEQ', 'VARCHAR', 15, '2026-09-13 04:55:59.290', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (41, 'IncludeAnalyzed', 'BIT', 17, '2026-09-13 04:55:59.317', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (42, 'ProcessRecordID', 'BIGINT', 18, '2026-09-13 04:55:59.330', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (43, 'RecipeID', 'INT', 19, '2026-09-13 04:55:59.347', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (44, 'StationID', 'INT', 20, '2026-09-13 04:55:59.387', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (45, 'SoftwareNumVer', 'VARCHAR', 20, '2026-09-13 04:55:59.390', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (46, 'SoftwareVersion', 'VARCHAR', 20, '2026-09-13 04:55:59.397', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (47, 'StationEQ', 'VARCHAR', 20, '2026-09-13 04:55:59.403', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (48, 'StationEQ', 'VARCHAR', 21, '2026-09-13 04:55:59.423', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (49, 'SoftwareNumber', 'VARCHAR', 21, '2026-09-13 04:55:59.427', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (50, 'IncludeExpired', 'BIT', 21, '2026-09-13 04:55:59.433', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (51, 'StationRecordID', 'BIGINT', 22, '2026-09-13 04:55:59.453', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (52, 'StationEQNumber', 'VARCHAR', 22, '2026-09-13 04:55:59.457', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (53, 'OnlyProduction', 'BIT', 23, '2026-09-13 04:55:59.477', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (54, 'SxPartName', 'VARCHAR', 24, '2026-09-13 04:55:59.503', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (55, 'OnlyProduction', 'BIT', 24, '2026-09-13 04:55:59.510', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (56, 'ActiveOnly', 'BIT', 24, '2026-09-13 04:55:59.513', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (57, 'SxRecipeName', 'VARCHAR', 25, '2026-09-13 04:55:59.530', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (58, 'UFID', 'VARCHAR', 26, '2026-09-13 04:55:59.547', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (59, 'StationEQNumber', 'VARCHAR', 27, '2026-09-13 04:55:59.577', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (60, 'StationRecordID', 'BIGINT', 27, '2026-09-13 04:55:59.583', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (61, 'ProcessRecordID', 'BIGINT', 27, '2026-09-13 04:55:59.590', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (62, 'ErrorCode', 'VARCHAR', 27, '2026-09-13 04:55:59.593', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (63, 'ErrorMessage', 'VARCHAR', 27, '2026-09-13 04:55:59.600', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (64, 'StationEQNumber', 'VARCHAR', 28, '2026-09-13 04:55:59.643', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (65, 'StationRecordID', 'BIGINT', 28, '2026-09-13 04:55:59.650', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (66, 'ProcessRecordID', 'BIGINT', 28, '2026-09-13 04:55:59.657', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (67, 'EventDescription', 'VARCHAR', 28, '2026-09-13 04:55:59.663', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (68, 'RecordedDateTimeOffset', 'DATETIMEOFFSET', 28, '2026-09-13 04:55:59.673', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (69, 'ProcessRecordID', 'BIGINT', 29, '2026-09-13 04:55:59.693', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (70, 'ParameterName', 'VARCHAR', 29, '2026-09-13 04:55:59.700', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (71, 'Value', 'FLOAT', 29, '2026-09-13 04:55:59.703', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (72, 'ParameterResult', 'BIT', 29, '2026-09-13 04:55:59.713', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (73, 'MachineName', 'VARCHAR', 30, '2026-09-13 04:55:59.740', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (74, 'EQNumber', 'VARCHAR', 30, '2026-09-13 04:55:59.747', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (75, 'ProcessRecordID', 'BIGINT', 31, '2026-09-13 04:55:59.770', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (76, 'Analyzed', 'BIT', 31, '2026-09-13 04:55:59.777', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (77, 'ProcessRecordID', 'BIGINT', 32, '2026-09-13 04:55:59.793', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (78, 'StatusID', 'TINYINT', 32, '2026-09-13 04:55:59.800', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (79, 'TimeRemainingSeconds', 'INT', 32, '2026-09-13 04:55:59.807', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (80, 'EQSerialNumber', 'VARCHAR', 33, '2026-09-13 04:55:59.830', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (81, 'ProcessRecordID', 'BIGINT', 33, '2026-09-13 04:55:59.833', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (82, 'EnvironmentalName', 'VARCHAR', 33, '2026-09-13 04:55:59.840', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (83, 'Value', 'FLOAT', 33, '2026-09-13 04:55:59.847', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (84, 'RecordedDateTimeOffset', 'DATETIMEOFFSET', 33, '2026-09-13 04:55:59.850', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (85, 'tWaveFormData', 'WAVEFORMTABLETYPE', 34, '2026-09-13 04:55:59.873', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (86, 'IncludeTotalRowCount', 'BIT', 34, '2026-09-13 04:55:59.880', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (87, 'LTDDProcessRecordID', 'BIGINT', 35, '2026-09-13 04:55:59.900', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (88, 'Position', 'CHAR', 35, '2026-09-13 04:55:59.903', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (89, 'FlagID', 'INT', 35, '2026-09-13 04:55:59.910', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (90, 'RecordedDateTimeOffset', 'DATETIMEOFFSET', 35, '2026-09-13 04:55:59.913', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (91, 'StationID', 'INT', 36, '2026-09-13 04:55:59.967', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (92, 'ConfigName', 'VARCHAR', 36, '2026-09-13 04:55:59.970', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (93, 'SoftwareNumber', 'VARCHAR', 36, '2026-09-13 04:55:59.977', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (94, 'Value', 'VARCHAR', 36, '2026-09-13 04:55:59.980', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (95, 'UserID', 'VARCHAR', 36, '2026-09-13 04:55:59.987', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (96, 'SoftwareVersion', 'VARCHAR', 36, '2026-09-13 04:55:59.993', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (97, 'StationEQ', 'VARCHAR', 36, '2026-09-13 04:56:00.000', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (98, 'StationEQ', 'VARCHAR', 37, '2026-09-13 04:56:00.017', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (99, 'tStationProcessSoftware', 'STATIONPROCESSSOFTWARETABLETYPE', 37, '2026-09-13 04:56:00.020', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (100, 'StationID', 'INT', 38, '2026-09-13 04:56:00.140', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (101, 'MtPartNumber', 'VARCHAR', 38, '2026-09-13 04:56:00.147', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (102, 'MtLotNumber', 'VARCHAR', 38, '2026-09-13 04:56:00.153', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (103, 'LotTypeID', 'TINYINT', 38, '2026-09-13 04:56:00.160', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (104, 'Quantity', 'FLOAT', 38, '2026-09-13 04:56:00.163', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (105, 'PartVersion', 'VARCHAR', 38, '2026-09-13 04:56:00.170', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (106, 'PartDescription', 'VARCHAR', 38, '2026-09-13 04:56:00.173', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (107, 'ExpirationDate', 'DATETIME2', 38, '2026-09-13 04:56:00.180', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (108, 'FeederName', 'VARCHAR', 38, '2026-09-13 04:56:00.187', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (109, 'LotAllocationType', 'VARCHAR', 38, '2026-09-13 04:56:00.190', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (110, 'StationEQ', 'VARCHAR', 38, '2026-09-13 04:56:00.197', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (111, 'StationID', 'INT', 39, '2026-09-13 04:56:00.217', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (112, 'UserID', 'VARCHAR', 39, '2026-09-13 04:56:00.223', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (113, 'WhenOffset', 'DATETIMEOFFSET', 39, '2026-09-13 04:56:00.230', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (114, 'StationEQ', 'VARCHAR', 39, '2026-09-13 04:56:00.233', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (115, 'StationID', 'INT', 40, '2026-09-13 04:56:00.277', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (116, 'UserID', 'VARCHAR', 40, '2026-09-13 04:56:00.283', 'DB_AutoSync', NULL, NULL, 1);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (117, 'WhenOffset', 'DATETIMEOFFSET', 40, '2026-09-13 04:56:00.287', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (118, 'StationEQ', 'VARCHAR', 40, '2026-09-13 04:56:00.293', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (119, 'LogoutReasonID', 'TINYINT', 40, '2026-09-13 04:56:00.300', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (120, 'LogoutReasonCode', 'VARCHAR', 40, '2026-09-13 04:56:00.303', 'DB_AutoSync', NULL, NULL, 0);
INSERT INTO [API].[FunctionParameters] ([param_id], [param_name], [data_type], [function_id], [date_created], [created_by], [last_date_modified], [last_modified_by], [required_param]) VALUES (121, 'LogoutComment', 'VARCHAR', 40, '2026-09-13 04:56:00.310', 'DB_AutoSync', NULL, NULL, 0);

SET IDENTITY_INSERT [API].[FunctionParameters] OFF;

-- ====================================
-- Data for [API].[FunctionsList]
-- ====================================

SET IDENTITY_INSERT [API].[FunctionsList] ON;

INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (1, 'CloseCradleSession', '2026-09-13 04:55:58.750', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (2, 'CloseProcessRecord', '2026-09-13 04:55:58.830', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (3, 'CreateCradleSession', '2026-09-13 04:55:58.883', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (4, 'CreateProcessRecord', '2026-09-13 04:55:58.910', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (5, 'CreateStationRecord', '2026-09-13 04:55:58.960', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (6, 'GetBathRecipeList', '2026-09-13 04:55:59.020', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (7, 'GetBathRecipeParameters', '2026-09-13 04:55:59.070', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (8, 'GetCradleStatus', '2026-09-13 04:55:59.087', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (9, 'GetEnvironmentalValues', '2026-09-13 04:55:59.103', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (10, 'GetLogoutReasons', '2026-09-13 04:55:59.150', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (11, 'GetLtdWaveform', '2026-09-13 04:55:59.170', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (12, 'GetLtdWaveformFlagReasons', '2026-09-13 04:55:59.203', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (13, 'GetLtdWaveformFlags', '2026-09-13 04:55:59.220', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (14, 'GetMachineEQ', '2026-09-13 04:55:59.263', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (15, 'GetModuleStatus', '2026-09-13 04:55:59.280', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (16, 'GetOpenCradleSessions', '2026-09-13 04:55:59.297', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (17, 'GetOpenProcessRecords', '2026-09-13 04:55:59.303', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (18, 'GetProcessRecordClose', '2026-09-13 04:55:59.320', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (19, 'GetRecipeParameters', '2026-09-13 04:55:59.337', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (20, 'GetStationConfig', '2026-09-13 04:55:59.350', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (21, 'GetStationProcessSoftware', '2026-09-13 04:55:59.410', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (22, 'GetStationRecord', '2026-09-13 04:55:59.440', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (23, 'GetSxPartList', '2026-09-13 04:55:59.467', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (24, 'GetSxRecipeList', '2026-09-13 04:55:59.483', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (25, 'GetSxRecipeParameters', '2026-09-13 04:55:59.520', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (26, 'GetUfStatus', '2026-09-13 04:55:59.537', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (27, 'LogError', '2026-09-13 04:55:59.553', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (28, 'LogEvent', '2026-09-13 04:55:59.607', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (29, 'LogProcessValue', '2026-09-13 04:55:59.677', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (30, 'RegisterStation', '2026-09-13 04:55:59.723', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (31, 'SetDataCollectionAnalyzed', '2026-09-13 04:55:59.753', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (32, 'SetDataCollectionStatus', '2026-09-13 04:55:59.783', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (33, 'SetEnvironmentalValue', '2026-09-13 04:55:59.813', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (34, 'SetLtdWaveform', '2026-09-13 04:55:59.857', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (35, 'SetLtdWaveformFlag', '2026-09-13 04:55:59.887', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (36, 'SetStationConfig', '2026-09-13 04:55:59.920', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (37, 'SetStationProcessSoftware', '2026-09-13 04:56:00.003', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (38, 'SetSubComponentLoaded', '2026-09-13 04:56:00.027', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (39, 'SetUserLogin', '2026-09-13 04:56:00.203', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (40, 'SetUserLogout', '2026-09-13 04:56:00.240', 'DB_AutoSync', NULL, NULL, 0, 'Database', '', 'Averna_mfgdb', 'LTDD', 0);
INSERT INTO [API].[FunctionsList] ([function_id], [function_name], [date_created], [created_by], [last_date_modified], [last_modified_by], [validated], [sys_interface], [custom_function_name], [database_name], [database_schema], [removed]) VALUES (41, 'TestFunc', '2026-09-13 05:01:32.403', 'User-Interface', NULL, NULL, 0, 'Database', '', 'TestDB', 'TestSchema', 0);

SET IDENTITY_INSERT [API].[FunctionsList] OFF;

-- ====================================
-- Data for [API].[Equipment]
-- ====================================

SET IDENTITY_INSERT [API].[Equipment] ON;

INSERT INTO [API].[Equipment] ([equipment_id], [equipment_name], [description], [date_created], [created_by], [last_date_modified], [active], [removed], [assigned]) VALUES (1, 'EQ-Bolt000-0002', 'BoltEquipment', '2026-09-13 06:08:23.310', NULL, '2026-09-13 06:08:23.310', 1, 0, 1);
INSERT INTO [API].[Equipment] ([equipment_id], [equipment_name], [description], [date_created], [created_by], [last_date_modified], [active], [removed], [assigned]) VALUES (2, 'EQ-Bolt000-0003', 'BoltEquipment', '2026-09-13 06:08:23.323', NULL, '2026-09-13 06:08:23.323', 1, 0, 1);
INSERT INTO [API].[Equipment] ([equipment_id], [equipment_name], [description], [date_created], [created_by], [last_date_modified], [active], [removed], [assigned]) VALUES (3, 'EQ-Bolt000-0004', 'BoltEquipment', '2026-09-13 06:08:23.330', NULL, '2026-09-13 06:08:23.330', 1, 0, 1);
INSERT INTO [API].[Equipment] ([equipment_id], [equipment_name], [description], [date_created], [created_by], [last_date_modified], [active], [removed], [assigned]) VALUES (4, 'EQ-Bolt000-000599', 'BoltEquipment', '2026-09-13 06:08:23.337', NULL, '2026-09-13 06:15:25.810', 0, 0, 1);
INSERT INTO [API].[Equipment] ([equipment_id], [equipment_name], [description], [date_created], [created_by], [last_date_modified], [active], [removed], [assigned]) VALUES (5, 'EQ-Bolt000-0006', 'BoltEquipment', '2026-09-13 06:08:23.340', NULL, '2026-09-13 06:08:23.340', 1, 1, 0);

SET IDENTITY_INSERT [API].[Equipment] OFF;

-- ====================================
-- Data for [API].[EquipmentGroups]
-- ====================================

SET IDENTITY_INSERT [API].[EquipmentGroups] ON;

INSERT INTO [API].[EquipmentGroups] ([equipment_group_id], [equipment_group_name], [date_created], [created_by], [last_date_modified], [active], [assigned]) VALUES (2, 'EG-Boltt-Test', '2026-09-13 08:03:34.543', NULL, '2026-09-13 08:03:34.543', 1, 1);

SET IDENTITY_INSERT [API].[EquipmentGroups] OFF;

-- ====================================
-- Data for [API].[EquipmentGroupList]
-- ====================================
INSERT INTO [API].[EquipmentGroupList] ([equipment_group_id], [equipment_id]) VALUES (2, 1);
INSERT INTO [API].[EquipmentGroupList] ([equipment_group_id], [equipment_id]) VALUES (2, 2);
INSERT INTO [API].[EquipmentGroupList] ([equipment_group_id], [equipment_id]) VALUES (2, 3);
INSERT INTO [API].[EquipmentGroupList] ([equipment_group_id], [equipment_id]) VALUES (2, 4);

-- ====================================
-- Data for [API].[FunctionGroups]
-- ====================================

SET IDENTITY_INSERT [API].[FunctionGroups] ON;

INSERT INTO [API].[FunctionGroups] ([function_group_id], [function_group_name], [date_created], [created_by], [last_date_modified], [active], [assigned]) VALUES (2, 'FG-Test', '2026-09-13 08:20:24.990', NULL, '2026-09-13 08:20:24.990', 1, 0);

SET IDENTITY_INSERT [API].[FunctionGroups] OFF;

-- ====================================
-- Data for [API].[FunctionGroupList]
-- ====================================
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 2);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 3);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 4);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 5);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 6);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 7);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 8);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 9);
INSERT INTO [API].[FunctionGroupList] ([function_group_id], [function_id]) VALUES (2, 10);

-- ====================================
-- Data for [API].[EquipmentFunctionAssignments]
-- ====================================

SET IDENTITY_INSERT [API].[EquipmentFunctionAssignments] ON;

INSERT INTO [API].[EquipmentFunctionAssignments] ([assignment_id], [assignment_name], [equipment_group_id], [function_group_id], [date_created], [created_by], [last_date_modified], [active]) VALUES (3, 'Ass1-test', 2, 2, '2026-09-13 08:27:33.367', NULL, '2026-09-13 08:27:33.367', 1);

SET IDENTITY_INSERT [API].[EquipmentFunctionAssignments] OFF;"""